name: Test

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "1.21", "1.22"]
    steps:
      - name: Install Go
        uses: actions/setup-go@5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test -race
